### ISSUE TITLE
Negative Values Missing

### ISSUE THREAD

**Issue by AzureOnyxscore** [NuggoDEV/DebrisTweaks-PC#1]
In the Quest version of Debris Tweaks, users were able to change the direction of the debris, allowing the debris to go away from the player rather than towards the player. This was achieved by decreasing the Velocity Multiplier to a negative value.

**Comment by NuggoDEV** [comment]
Was just about to make a new release, glad I caught this! I'll add this in quickly

**Comment by NuggoDEV** [comment]
Alrighty released with the updated velocity as well
https://github.com/NuggoDEV/DebrisTweaks-PC/releases/tag/v1.1.0
